name: Build Pull Request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package
      - name: Archive artifacts (Cumulus Api)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Cumulus Api
          path: api/target/cumulus-api.jar
      - name: Archive artifacts (Cumulus Impl)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Cumulus Implementation
          path: impl/target/cumulus-impl.jar
