name: Build Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Archive Cumulus artifact
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: Cumulus
          path: build/libs/cumulus-*.jar
